/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    Search: typeof import('./src/components/search/search.vue')['default']
    Tabbar: typeof import('./src/components/tab-bar/tabbar.vue')['default']
  }
}
